name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest  # Use a Windows runner to build the .exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from CHANGELOG
        id: get_version
        run: |
          $version = (Get-Content -Path CHANGELOG.md -TotalCount 1).Trim()
          echo "VERSION=$version" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Check if release tag already exists
        id: check_tag
        uses: mukunku/tag-exists-action@v1.4.0
        with:
          tag: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the application if tag is new
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          # Setup .NET 8 SDK
          & "D:\a\_actions\actions\setup-dotnet\v4\bin\setup-dotnet.cmd" '8.0'
          
          # Run the build script
          ./build.ps1
        shell: pwsh

      - name: Create GitHub Release and Upload Asset
        if: steps.check_tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          files: bin/Release/net8.0-windows10.0.19041.0/win-x64/publish/SuzerainSaveEditor.exe
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body_path: CHANGELOG.md
          prerelease: false